services:
  app:
    image: ghcr.io/windrider-psd/pedido-certo-api:main
    container_name: bun-app-prod
    ports:
      - "6969:6969"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    command: bun run dist/index.js

  db:
    image: postgres:17
    container_name: postgres-prod
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "6000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
